### ISSUE TITLE
Task: Always add a quality setting in url

### ISSUE THREAD

**Issue by christophlehmann** [networkteam/Networkteam.ImageProxy#2]
An url should always contain a quality setting. 

If i see it correct, it may not be the case, see https://github.com/networkteam/Networkteam.ImageProxy/blob/main/Classes/Aspects/ThumbnailAspect.php#L73

If quality is not set, then a new setting `formatQuality` should be checked. (= url parameter `format_quality`)

If defined then add https://docs.imgproxy.net/generating_the_url?id=format-quality to the url.

```yaml
Networkteam:
  ImageProxy:
    # New setting, Example: 'jpg=75,avif=80,webp=70'
    formatQuality: ''
```

If undefined, use `Neos.Media.image.defaultOptions.quality` as `quality` url parameter
