### ISSUE TITLE
Feature: Auto-resize images during import in Neos

### ISSUE THREAD

**Issue by christophlehmann** [networkteam/Networkteam.ImageProxy#8]
Realize new setting

```
Networkteam:
  ImageProxy:
    # Resize images during upload. A value of 4096 means the image becomes a width/height of 4096 pixel. A value of 0 disables resizing
    autoResizeDuringUpload: 4096
```

Make sure that quality, meta data and aspect ratio remains the same.
